# Generated by Django 3.1.5 on 2021-02-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
